" Wraps paths to make them relative to this directory.
function! Dot(path)
  return '~/.vim/config/' . a:path
endfunction

let configs = [
  \'plugins.vim',
  \'general.vim',
  \'mappings.vim',
  \'filetypes.vim',
  \'colors.vim',
  \'functions.vim'
\]

" Load all configuration modules.
for file in configs
  execute 'source' Dot(file)
endfor

execute 'luafile' Dot('lsp-setup.lua')
execute 'luafile' Dot('mappings/which-key.lua')
