# Path to your oh-my-zsh installation.
export ZSH=/Users/sendyhalim/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git vi-mode theme)

# User configuration

# http://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm
# https://github.com/rvm/rvm/issues/3212
export PATH="$PATH:/Users/sendyhalim/.gvm/bin:/Users/sendyhalim/.pyenv/shims:/Users/sendyhalim/.rvm/gems/ruby-2.2.2/bin:/Users/sendyhalim/.rvm/gems/ruby-2.2.2@global/bin:/Users/sendyhalim/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sendyhalim/.rvm/bin:/Users/sendyhalim/.rvm/bin:/Users/sendyhalim/.rvm/bin:/Users/sendyhalim/development/tools/arc/arcanist/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


# Set Variables
export HOMEBREW_PREFIX=$(brew --prefix)

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Alias for starting mongodb
alias start-mongodb="mongod --config /usr/local/etc/mongod.conf"

export PATH="$PATH:$HOME/development/tools/arc/arcanist/bin"
export PATH="$PATH:/usr/local/opt/php56/bin"
export EDITOR="/usr/local/bin/vim"


# Node Version Manager
# source $(brew --prefix nvm)/nvm.sh
export NVM_DIR="/Users/sendyhalim/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Rust Version Manager
[[ -s /Users/sendyhalim/.rsvm/rsvm.sh ]] && . /Users/sendyhalim/.rsvm/rsvm.sh # This loads RSVM

# For vim-racer
export RUST_SRC_PATH="/Users/sendyhalim/development/git-repos/rust/src"

# Do not share history between terminals
setopt no_share_history
