# ZSH Styles
ZSH_HIGHLIGHT_STYLES[command]=fg=39
ZSH_HIGHLIGHT_STYLES[builtin]=fg=39
ZSH_HIGHLIGHT_STYLES[alias]=fg=106
ZSH_HIGHLIGHT_STYLES[globbing]=fg=140
ZSH_HIGHLIGHT_STYLES[path]=fg=102
ZSH_HIGHLIGHT_STYLES[comment]=fg=244

